version: '3.7'
services:

  sage-ecr:
    image: waggle/sage-ecr:latest
    build: .
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/app  # for development only
    restart: always
    networks:
      - sage-ecr
    environment:
      # test suite requires this to be set to prevent accidentally wiping production database and registry
      TESTING: "true"

      # database settings
      MYSQL_HOST: db
      MYSQL_DATABASE: SageECR
      MYSQL_USER: sage
      MYSQL_PASSWORD: test

      # jenkins settings
      JENKINS_SERVER: http://jenkins:8080
      JENKINS_USER: ecrdb
      JENKINS_TOKEN: test

      # registry settings
      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
      DOCKER_REGISTRY_URL: "registry:5000"
      DOCKER_REGISTRY_PUSH_ALLOWED: "1"
      DOCKER_REGISTRY_INSECURE: "1"

      # buildkit settings
      BUILDKITD_ADDR: "tcp://buildkitd:1234"

      # auth settings (not used for local testing)
      AUTH_METHOD: ${AUTH_METHOD}
      tokenInfoEndpoint: ${SageTokenInfoEndpoint}
      tokenInfoUser: ${SageTokenInfoUser}
      tokenInfoPassword: ${SageTokenInfoPassword}

      # s3 settings (not used in local testing)
      ADD_USER: ${ADD_USER}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_FOLDER: ${S3_FOLDER}

  db:
    image: mysql
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: SageECR
      MYSQL_PASSWORD: test
      MYSQL_USER: sage
    networks:
      - sage-ecr

  jenkins:
    image: waggle/ecr-jenkins:1.0.0
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      - CASC_JENKINS_CONFIG=/config/casc_jenkins.yaml
      - JAVA_OPTS=-Dhudson.footerURL=http://localhost:8082 -Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins/casc_jenkins.yaml:/config/casc_jenkins.yaml:ro
    networks:
      - sage-ecr

  registry:
    restart: always
    image: registry:2
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true # allows us to delete manifests between unit tests
    networks:
      - sage-ecr

  buildkitd:
    image: moby/buildkit:latest
    command:
      - --addr
      - tcp://0.0.0.0:1234
    # double check the actual capabilities needed
    privileged: true
    networks:
      - sage-ecr

networks:
  sage-ecr:
   name: sage-ecr
