version: '3.7'
services:

  sage-ecr:
    image: waggle/sage-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/usr/src/app  # for development only
    restart: always
    networks:
      - sage-ecr
    environment:
      AUTH_METHOD: ${AUTH_METHOD}

      tokenInfoEndpoint: ${SageTokenInfoEndpoint}
      tokenInfoUser: ${SageTokenInfoUser}
      tokenInfoPassword: ${SageTokenInfoPassword}

      # database config
      MYSQL_HOST: db
      MYSQL_DATABASE: SageECR
      MYSQL_PASSWORD: test
      MYSQL_USER: sage

      # jenkins config
      JENKINS_SERVER: ${JENKINS_SERVER}
      JENKINS_USER: ecrdb
      JENKINS_TOKEN: ${JENKINS_TOKEN}

      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
      DOCKER_REGISTRY_URL: "registry:5002"

      ADD_USER: ${ADD_USER}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_FOLDER: ${S3_FOLDER}

  db:
    image: mysql
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: SageECR
      MYSQL_PASSWORD: test
      MYSQL_USER: sage
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - sage-ecr-db:/var/lib/mysql
    networks:
      - sage-ecr
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  registry:
    restart: always
    image: registry:2
    networks:
      - sage-ecr

  jenkins:
    image: waggle/ecr-jenkins
    build: jenkins
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
      - "127.0.0.1:50000:50000"
    environment:
      - DOCKER_REGISTRY_INSECURE=1
      - JAVA_OPTS=-Dhudson.footerURL=http://localhost:8082
      - CASC_JENKINS_CONFIG=/config/casc_jenkins.yaml
    volumes:
      - ./jenkins/casc_jenkins.yaml:/config/casc_jenkins.yaml:ro
    networks:
      - sage-ecr
    # converting from
    # --env -p 8082:8080  -p 50000:50000 -v `pwd`/jenkins/casc_jenkins.yaml:/config/casc_jenkins.yaml:ro -v `pwd`/temp:/docker:rw -v /var/run/docker.sock:/var/run/docker.sock ${DOCKER_MOUNT} waggle/ecr-jenkins

  buildkitd:
    image: moby/buildkit:latest
    command:
      - --addr
      - tcp://0.0.0.0:1234
    # double check the actual capabilities needed
    privileged: true
    networks:
      - sage-ecr

# test commands... should perform this as as unit test?
# cd /root && git clone https://github.com/waggle-sensor/plugin-test-pipeline
#
# buildctl --addr tcp://buildkitd:1234 build --frontend=dockerfile.v0 --opt platform=linux/amd64,linux/arm64 --local context=. --local dockerfile=. --output type=image,name=test-pipeline
# buildctl --addr tcp://buildkitd:1234 build --frontend=dockerfile.v0 --opt platform=linux/amd64,linux/arm64 --local context=. --local dockerfile=. --output type=image,name=registry:5000/x/test-pipeline,push=true
# buildctl --addr tcp://buildkitd:1234 build --frontend=dockerfile.v0 --opt platform=linux/amd64,linux/arm64 --local context=. --local dockerfile=. --output type=image,name=registry.sagecontinuum.org/x/test-pipeline,push=true

volumes:
  sage-ecr-db:

networks:
  sage-ecr:
   name: sage-ecr
