
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: start environment
      run: make start

    - name: wait for environment
      run: sleep 10

    - name: run tests and coverage
      run: make test-no-tty

